/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;

/**
 *
 * @author Mario Rodríguez
 */
public class TreasureView extends javax.swing.JPanel {

    Treasure treasureModel ;
    private boolean selected = false ;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    public boolean isSelected()
    {
        return this.selected ;
    }
    
    public Treasure getTreasure()
    {
        return this.treasureModel ;
    }
    
    // Recibe como parámetro un Treasure y actualiza los componentes que forman parte del diseño de su vista.
    public void setTreasure (Treasure t) {
        setBackground(new java.awt.Color(199, 233, 192)) ;
        treasureModel = t;
        String cadena = ( "Tipo:  " + treasureModel.getType() ) ;
        nombre.setText( "Nombre:  " + treasureModel.getName() ) ;
        piezasOro.setText( "Monedas de oro:  " + Integer.toString( treasureModel.getGoldCoins() ) ) ;
        bonusMax.setText( "Bonus Máximo:  " + Integer.toString( treasureModel.getMaxBonus() ) ) ;
        bonusMin.setText( "Bonus Mínimo:  " + Integer.toString( treasureModel.getMinBonus() ) ) ;
        tipo.setText( cadena ) ;
        this.setOpaque(selected);
        repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        bonusMax = new javax.swing.JLabel();
        bonusMin = new javax.swing.JLabel();
        piezasOro = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        nombre.setText("Nombre");

        bonusMax.setText("Bonus máximo");

        bonusMin.setText("Bonus mínimo");

        piezasOro.setText("Piezas de oro");

        tipo.setText("Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipo)
                    .addComponent(piezasOro)
                    .addComponent(bonusMin)
                    .addComponent(bonusMax)
                    .addComponent(nombre))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nombre)
                .addGap(18, 18, 18)
                .addComponent(bonusMax)
                .addGap(18, 18, 18)
                .addComponent(bonusMin)
                .addGap(18, 18, 18)
                .addComponent(piezasOro)
                .addGap(18, 18, 18)
                .addComponent(tipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if( this.selected == true )
            this.selected = false ;
        else
            this.selected = true ;
        
        this.setOpaque(selected);         
        repaint();
        revalidate();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonusMax;
    private javax.swing.JLabel bonusMin;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel piezasOro;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
