/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Cultist;
import NapakalakiGame.CultistPlayer;
import NapakalakiGame.Player;

/**
 *
 * @author Mario Rodríguez
 */
public class CultistView extends javax.swing.JPanel {

    private Cultist cultistModel ;
    /**
     * Creates new form CultistView
     */
    public CultistView() {
        initComponents();
    }
    
    // Recibe como parámetro un Treasure y actualiza los componentes que forman parte del diseño de su vista.
    public void setCultist (Player p) {
        
        if( p instanceof CultistPlayer )
        {
            CultistPlayer cp = ( CultistPlayer )p ;
            this.cultistModel = cp.getCultistCard() ;
            nombre.setText( "Nombre:  " + cultistModel.getName() ) ;
            basicValue.setText( "Valor Básico:  " + cultistModel.getBasicValue() ) ;
            valorSpecial.setText( "Valor Especial:  " + cultistModel.getSpecialValue() + " por cada sectario en juego." ) ;
            repaint() ;
            revalidate() ;
        }
        else
        {
            this.cultistModel = null ;        
            nombre.setText( " " ) ;
            basicValue.setText(  " "  ) ;
            valorSpecial.setText(  " "  ) ;
            repaint() ;
            revalidate() ;        
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        basicValue = new javax.swing.JLabel();
        valorSpecial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        nombre.setText("nombre");

        basicValue.setText("basicValue");

        valorSpecial.setText("specialValue");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sectario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(valorSpecial)
                    .addComponent(basicValue)
                    .addComponent(nombre))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre)
                .addGap(18, 18, 18)
                .addComponent(basicValue)
                .addGap(18, 18, 18)
                .addComponent(valorSpecial)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basicValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel valorSpecial;
    // End of variables declaration//GEN-END:variables
}
