/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Dice;
import NapakalakiGame.Napakalaki;

/**
 *
 * @author Mario 
 */
public class NapakalakiView extends javax.swing.JFrame {
    
    private Napakalaki napakalakiModel ;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }
        
    public  void setNapakalaki( Napakalaki obj ) 
    {
       this.napakalakiModel = obj ;
       this.playerView2.setNapakalaki(obj);
       this.playerView2.setPlayer(obj.getCurrentPlayer());
       this.combate.setEnabled(false);
       this.siguienteT.setEnabled(false);
       this.repaint();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verMonstruo = new javax.swing.JButton();
        combate = new javax.swing.JButton();
        siguienteT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultCombat = new javax.swing.JLabel();
        monsterView1 = new GUI.MonsterView();
        jSeparator2 = new javax.swing.JSeparator();
        playerView2 = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        verMonstruo.setText("Ver monstruo");
        verMonstruo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMonstruoActionPerformed(evt);
            }
        });

        combate.setText("Combate");
        combate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combateActionPerformed(evt);
            }
        });

        siguienteT.setText("Siguiente turno");
        siguienteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteTActionPerformed(evt);
            }
        });

        jButton1.setText("Salir del juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NAPAKALAKI GAME");
        jLabel1.setToolTipText("");

        resultCombat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verMonstruo)
                            .addComponent(siguienteT))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(verMonstruo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(combate)
                    .addComponent(resultCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siguienteT)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteTActionPerformed
        // TODO add your handling code here:
        if( this.napakalakiModel.nextTurn() ){        
            this.resultCombat.setText("Turno de " + this.napakalakiModel.getCurrentPlayer().getName());
            this.setNapakalaki(napakalakiModel);
            this.verMonstruo.setEnabled(true);
        }
        else
        {            
            this.resultCombat.setText("No has cumplido el mal rollo o tienes mas de 4 tesoros ocultos");
            this.setNapakalaki(napakalakiModel);
            this.siguienteT.setEnabled(true);
            this.verMonstruo.setEnabled(false);            
        }        
    }//GEN-LAST:event_siguienteTActionPerformed

    private void verMonstruoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMonstruoActionPerformed
        // TODO add your handling code here:
        
        this.siguienteT.setEnabled(false);
        this.monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        this.combate.setEnabled(true);        
    }//GEN-LAST:event_verMonstruoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combateActionPerformed
        // TODO add your handling code here:
        this.combate.setEnabled(false);       
        CombatResult result = napakalakiModel.developCombat();        
        String resultado = null;
        switch (result) {
            case WinAndWinGame : 
              resultado = "\n\n ¡¡¡ H A S   G A N A D O   L A   P A R T I D A !!!";
              break;
            case Win :
              resultado = "\n\n Ganaste el combate";
              break;
            case Lose :
              resultado = "\n\n Has perdido el combate, te toca cumplir el mal rollo";
              break;
            case LoseAndEscape :
              resultado = "\n\n Perdiste el combate pero has logrado escapar";
              break;
            case LoseAndDie :
              resultado = "\n\n Perdiste el combate y además estás muerto";
              break;
            case LoseAndConvert :
              resultado = "\n\n Ahora eres un SECTARIO.";
              break;
        }
        this.resultCombat.setText(resultado);
        this.setNapakalaki(napakalakiModel);
        this.verMonstruo.setEnabled(false);
        this.siguienteT.setEnabled(true);
    }//GEN-LAST:event_combateActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showView() 
    {
        this.setVisible( true ) ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView2;
    private javax.swing.JLabel resultCombat;
    private javax.swing.JButton siguienteT;
    private javax.swing.JButton verMonstruo;
    // End of variables declaration//GEN-END:variables
}
